### ISSUE TITLE
Create Simple Orchestrator

### ISSUE THREAD

**Issue by maxwey** [NGCP/GCS#36]
Create a simple orchestrator. This should be able to have a list of vehicles and a list of missions. 

It should assign a mission on a start trigger, and have a callback that will assign the next mission.

Should update vehicles with the update message. 
Orchestrator should not hang!

**Comment by kedwinchen** [comment]
[In progress]
- [x] Add basic framework for core functionality
- [x] Add basic logic for message handling
- [x] Finish implementing logic for sending, receiving messages
- [x] (?) Create a basic Vehicle class to meet requirements of Orchestrator class

**Comment by Luis729** [comment]
Will be closed when `dev-2018-missionui` merges.
