### ISSUE TITLE
Update Message handling logic

### ISSUE THREAD

**Issue by kedwinchen** [NGCP/GCS#42]
MessageHandler
Types of messages (incoming)
- [x] Control
- [x] ACK (stop sending message, rcv'd)
- [x] vehicle-based (stuff the mission doesn't care about; e.g., battery level)
- [x] send to vehicle directly; do not do anything in orchestrator
- [x] mission-based (stuff the Vehicle doesn't care about; e.g., point of interest)
- [x] Vehicle/Mission (e.g., update)

- [x] Message Routing (Orchestrator?)

**Comment by maxwey** [comment]
See this doc: https://github.com/NGCP/GCS/wiki/GCS-JSON-Messages-(Official)

**Comment by Luis729** [comment]
MessageHandler processes all messages properly

sending:
- will send the message over and over again until it is acknowledged (currently sends that message at a rate of 10 times a second, I see VTOL only sends once a second, so we might change this send rate)
  - excludes `ack` and `badMessage`, only sends these once

receiving:
- sends `badMessage` to wrong message types
   - logs if received message that (1) is not a json (2) is a json but no `sid` to send back to origin
- will not acknowledge `ack` `badMessage` messages
- will forward `connect` `update` `poi` `complete` messages to Orchestrator

https://github.com/NGCP/GCS/blob/dev-2018-missionui-orchestrator/src/common/MessageHandler.ts
