### ISSUE TITLE
Add a light theme to UI

### ISSUE THREAD

**Issue by tnleang** [NGCP/GCS#50]
Adding a switch from the dark theme (currently our UI theme) to a light theme.
The switch serves as toggle between dark and light theme.

**Comment by tnleang** [comment]
Adding a switch from the dark theme (currently our UI theme) to a light theme.
The switch serves as toggle between dark and light theme.

**Comment by Luis729** [comment]
Addressed by https://github.com/NGCP/GCS/commit/482db1a660f367900b237c4cb16f2f5f98637fce

Colors need to be enhanced more. Still feels like its in beta. Should be finished this week.

One more thing to address is that code should be tested (in this case just making sure that there are no linting errors) before committing the code. There shouldnt be random merges either, a random thing I saw in the latest commit.

**Comment by maquino123** [comment]
Addresses #50

Log Container needs improvement and we are adding small color changes to Mission and Vehicle container.
