### ISSUE TITLE
Change all occurrences of single quotes JSON in wiki into double quotes

### ISSUE THREAD

**Issue by LucasYoung** [NGCP/GCS#51]
Single quotes are not accepted in JSON format so we should change all occurrences of this in the wiki.
[Source](https://stackoverflow.com/a/4162651)

**Comment by Luis729** [comment]
Resolved https://github.com/NGCP/GCS/wiki/GCS-JSON-Messages/d88b1010d6b6747c0003f2ea94101ba9408caf09
